### ISSUE TITLE
List my pages at the root of my subdomain

### ISSUE THREAD

**Issue by joshski** [AndrewVos/anmo#1]
or at least http://joshski.anmo.io should be less broken by default

**Comment by AndrewVos** [comment]
Ahh, so you have to create a page with a path of "/" and do this yourself.

**Comment by joshski** [comment]
Seems to me you could explain that somewhere.

What about serving up a "create page" form with any 404? Send a 404 status code, but if the user is the owner of the site, also render a form with a "create this page" button on it... that would be nice. Dunno how difficult.

**Comment by AndrewVos** [comment]
OOOOOOOH clever! That's amazing I love it

**Comment by joshski** [comment]
Hehe not really my idea, this is how wikis used to work, back when wikis were good.
